package de.uni.konstanz.eventdescriptors;

public enum EventDescriptorType {
	POSITIVE_SENTIMENT, NEGATIVE_SENTIMENT, NEUTRAL_SENTIMENT, CONVERSATIONAL, 
	POPULAR, URL_DENSITY, HASHTAG_DENSITY, OBJECTIVITY, PRESENT_ORRIENTED, 
	PAST_ORIENTED, LOCATION_SUPPORT, RETWEET_DENSTIY,MOBILE_SUPPORT, 
	DIFFERENT_USERS, WEIRD_CHARS_SATURATION, QUESTIONING, EMOTICONS_SATURATION,
	SWEARING_WORDS_SATURATION, SLANGS_SATURATION, INTENSIFICATION,GEO_META_SUPPORT,
	TWEETS_LENGTH, POPULAR_USERS_SUPPORT, ACTIVE_USERS_SUPPORT, DESCRIBED_USERS_SUPPORT,
	NEAR_USERS_SUPPORT
	
}


